name: CI/CD for SimpleTimeService

on:
push:
branches:
- main

env:
AWS_REGION: us-east-1
IMAGE_NAME: simpletimeservice
DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
build-and-deploy:
runs-on: ubuntu-latest

steps:
- name: Checkout Code
uses: actions/checkout@v3

- name: Set up Docker
uses: docker/setup-buildx-action@v2

- name: Log in to Docker Hub
run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

- name: Build and Push Docker Image
run: |
docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest ./app
docker push $DOCKER_USERNAME/$IMAGE_NAME:latest

- name: Setup AWS Credentials
uses: aws-actions/configure-aws-credentials@v3
with:
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
aws-region: ${{ env.AWS_REGION }}

- name: Terraform Init
working-directory: ./terraform
run: terraform init

- name: Terraform Apply
working-directory: ./terraform
run: terraform apply -auto-approve

